### ISSUE TITLE
Callbacks Not Called Till All Jobs Completed

### ISSUE THREAD

**Issue by theory** [atoomic/Parallel-Subs#1]
I'm working on [a script](/theory/pgxn-build-test-reporter/blob/main/bin/build-test-reporter) that runs 300 jobs on 16 processes. The parallelism is great! However, the callback is not called as each job finishes, but only at the end, after all jobs have finished. I was hoping the output file would be written to as jobs finished.

Is this intentional? Is there some way I'm missing to have callbacks called as each sub finishes execution?

**Comment by atoomic** [comment]
Thanks @theory for reaching out.

The implementation of `Parallel::Subs` is pretty naive and a thin wrapper around [Parallel::ForkManager](https://metacpan.org/pod/Parallel::ForkManager).

So to answer to your question this is not intentional, patch welcome. But you should consider switching to `Parallel::ForkManager` for more advanced features available out of the box.

Thanks
Nicolas

**Comment by theory** [comment]
Thanks. Yeah I switched to Parallel::WorkUnit and that fixed the issue.
